FROM python:3.11-slim

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . /app/

RUN chmod +x /app/src/language_scrapers/python/*.sh

RUN pip install --upgrade pip
RUN pip install .

ENV PYTHONUNBUFFERED=1

CMD ["python", "-m", "processors.cfg_processor"]
