FROM python:3.11-slim

WORKDIR /app
COPY . /app/

RUN pip install --upgrade pip
RUN pip install .

ENV PYTHONUNBUFFERED=1
EXPOSE 8000

CMD ["uvicorn", "url_app.main:app", "--host", "0.0.0.0", "--port", "8000"]
