#!/bin/bash
set -e

REPO_URL=$1

BASE_DIR="$REPO_FOLDER"
mkdir -p "$BASE_DIR"
cd "$BASE_DIR"

REPO_DIR=$(basename "$REPO_URL" .git)

if [ -d "$REPO_DIR" ]; then
    echo "Removing existing directory: $REPO_DIR"
    rm -rf "$REPO_DIR"
fi

git clone --recurse-submodules "$REPO_URL"
BUILD_DIR="$BASE_DIR/$REPO_DIR/build"

mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"

cmake -S .. -B . -DCMAKE_CXX_STANDARD=17 -DCMAKE_C_STANDARD=99 -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

# Check if compile_commands.json was generated
if [ ! -f "compile_commands.json" ]; then
    echo "ERROR: compile_commands.json was not generated by CMake"
    exit 1
fi

cmake --build . || echo "Build failed, but compile_commands.json exists"